package com.fruitninja.hands

import android.Manifest
import android.content.pm.PackageManager
import android.os.Build
import android.system.Os
import android.system.OsConstants
import android.view.HapticFeedbackConstants
import androidx.core.content.ContextCompat
import com.facebook.react.bridge.Arguments
import com.facebook.react.bridge.LifecycleEventListener
import com.facebook.react.bridge.Promise
import com.facebook.react.bridge.ReactApplicationContext
import com.facebook.react.bridge.ReadableMap
import com.facebook.react.bridge.UiThreadUtil
import com.facebook.react.bridge.WritableMap
import java.util.concurrent.Executors

/**
 * TurboModule implementation (the abstract base is generated by React Native
 * codegen from src/specs/NativeFNHands.ts). It is a thin, typed facade over
 * [HandsController], which owns the camera.
 */
class HandsModule(private val context: ReactApplicationContext) :
    NativeFNHandsSpec(context), LifecycleEventListener {

    private val controller = HandsController(
        context,
        object : HandsController.EventSink {
            override fun onHandFrame(map: WritableMap) = emitOnHandFrame(map)
            override fun onState(map: WritableMap) = emitOnTrackingState(map)
        },
    )
    private val io = Executors.newSingleThreadExecutor { r -> Thread(r, "hands-module-io") }

    init {
        HandsRegistry.controller = controller
        context.addLifecycleEventListener(this)
    }

    override fun getCapabilities(promise: Promise) {
        io.execute {
            try {
                val model = ModelIntegrity.check(context)
                val map = Arguments.createMap()
                map.putBoolean("hasFrontCamera", Cameras.lensStatus(context, true) == Cameras.LensStatus.OK)
                map.putBoolean("hasBackCamera", Cameras.lensStatus(context, false) == Cameras.LensStatus.OK)
                map.putBoolean(
                    "cameraDisabled",
                    Cameras.lensStatus(context, true) == Cameras.LensStatus.DISABLED ||
                        Cameras.lensStatus(context, false) == Cameras.LensStatus.DISABLED,
                )
                map.putBoolean(
                    "permissionGranted",
                    ContextCompat.checkSelfPermission(context, Manifest.permission.CAMERA) ==
                        PackageManager.PERMISSION_GRANTED,
                )
                map.putBoolean("modelPresent", model.present)
                map.putBoolean("modelSha256Ok", model.ok)
                map.putString("modelSha256", model.sha256)
                map.putInt("sdkInt", Build.VERSION.SDK_INT)
                val abis = Arguments.createArray()
                Build.SUPPORTED_ABIS.forEach { abis.pushString(it) }
                map.putArray("supportedAbis", abis)
                map.putInt("pageSizeBytes", Os.sysconf(OsConstants._SC_PAGESIZE).toInt())
                map.putString("cameraXVersion", BuildConfig.CAMERAX_VERSION)
                map.putString("mediaPipeVersion", BuildConfig.MEDIAPIPE_VERSION)
                promise.resolve(map)
            } catch (t: Throwable) {
                promise.reject("E_CAPABILITIES", t.message ?: t.javaClass.simpleName, t)
            }
        }
    }

    override fun start(options: ReadableMap, promise: Promise) {
        val config = try {
            StartConfig(
                front = (options.getStringOrDefault("lens", "front")) != "back",
                numHands = options.getIntOrDefault("numHands", 2).coerceIn(1, 2),
                delegate = options.getStringOrDefault("delegate", "cpu"),
                minDetectionConfidence = options.getDoubleOrDefault("minDetectionConfidence", 0.65).toFloat(),
                minPresenceConfidence = options.getDoubleOrDefault("minPresenceConfidence", 0.5).toFloat(),
                minTrackingConfidence = options.getDoubleOrDefault("minTrackingConfidence", 0.65).toFloat(),
                analysisWidth = options.getIntOrDefault("analysisWidth", 640),
                analysisHeight = options.getIntOrDefault("analysisHeight", 480),
                maxInFlight = options.getIntOrDefault("maxInFlight", 1).coerceIn(1, 3),
                maxEmitHz = options.getIntOrDefault("maxEmitHz", 0).coerceAtLeast(0),
            )
        } catch (t: Throwable) {
            promise.reject("E_ARGS", t.message ?: "Invalid start options", t)
            return
        }
        controller.start(config, promise)
    }

    override fun stop(promise: Promise) {
        controller.stop("requested", promise)
    }

    override fun getStats(promise: Promise) {
        promise.resolve(controller.statsMap())
    }

    override fun haptic(kind: String) {
        val view = context.currentActivity?.window?.decorView ?: return
        val constant = when (kind) {
            "slice" -> HapticFeedbackConstants.CONTEXT_CLICK
            "bomb" -> HapticFeedbackConstants.LONG_PRESS
            "miss" -> HapticFeedbackConstants.CLOCK_TICK
            else -> return
        }
        UiThreadUtil.runOnUiThread { view.performHapticFeedback(constant) }
    }

    // The camera must never outlive the foreground activity.
    override fun onHostPause() = controller.stop("background")

    override fun onHostResume() = Unit

    override fun onHostDestroy() = controller.stop("destroyed")

    override fun invalidate() {
        context.removeLifecycleEventListener(this)
        controller.shutdown()
        if (HandsRegistry.controller === controller) {
            HandsRegistry.controller = null
        }
        io.shutdown()
        super.invalidate()
    }
}

private fun ReadableMap.getStringOrDefault(key: String, default: String): String =
    if (hasKey(key) && !isNull(key)) getString(key) ?: default else default

private fun ReadableMap.getIntOrDefault(key: String, default: Int): Int =
    if (hasKey(key) && !isNull(key)) getDouble(key).toInt() else default

private fun ReadableMap.getDoubleOrDefault(key: String, default: Double): Double =
    if (hasKey(key) && !isNull(key)) getDouble(key) else default
